# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: ci Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8.18"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        cd assignments/
        python -m pip install --upgrade pip
        pip install '.[dev]'
        
    - name: Test with pytest
      run: |
        pytest life_expectancy --cov

    - name: Lint with pylint
      run: |
        pylint life_expectancy.cleaning
